### ISSUE TITLE
Not working with V2 api of TADO

### ISSUE THREAD

**Issue by rodbartolo** [fuzzysb/Tado#4]
This is not working with the V2 api of TADO, or possibly not working if only one device is on TADO.

It seems like every character is being looped instead of the devices on method to initialise the devices and create them on ST

e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e  6:57:26 AM: error Error creating device: grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'physicalgraph.device.Device' on field 'deviceNetworkId': rejected value [o|null|4922065d-6ebe-4b46-a3ff-1250cafabce0]; codes [physicalgraph.device.Device.deviceNetworkId.unique.error.physicalgraph.device.Device.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.error.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.error.java.lang.String,physicalgraph.device.Device.deviceNetworkId.unique.error,device.deviceNetworkId.unique.error.physicalgraph.device.Device.deviceNetworkId,device.deviceNetworkId.unique.error.deviceNetworkId,device.deviceNetworkId.unique.error.java.lang.String,device.deviceNetworkId.unique.error,physicalgraph.device.Device.deviceNetworkId.unique.physicalgraph.device.Device.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.java.lang.String,physicalgraph.device.Device.deviceNetworkId.unique,device.deviceNetworkId.unique.physicalgraph.device.Device.deviceNetworkId,device.deviceNetworkId.unique.deviceNetworkId,device.deviceNetworkId.unique.java.lang.String,device.deviceNetworkId.unique,unique.physicalgraph.device.Device.deviceNetworkId,unique.deviceNetworkId,unique.java.lang.String,unique]; arguments [deviceNetworkId,class physicalgraph.device.Device,o|null|4922065d-6ebe-4b46-a3ff-1250cafabce0]; default message [{0} must be unique]

**Comment by fuzzysb** [comment]
there is no device information being passed. my device handler works with v2 of the api and can retrieve device types. what device do you have? I suspect you have issues with saving states in Smartthings which has been a bug with smarthings forever. I will get you some queries to test in insomnia rest client and.We can see where the issue lies based on the output

**Comment by fuzzysb** [comment]
I either way I could do with the full loot to see what commands you sent to get the list of devices

**Comment by rodbartolo** [comment]
Hi Stuart,
first of all, excellent work on this.  I have the Smart A/C controller.
The issue seems to be with parsing the Zones.

See below:
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:20 AM: debug Executing 'sendCommand.userStatusCommand'
6e3e69f7-27c1-451a-b42a-71ec98eda131
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#6e3e69f7-27c1-451a-b42a-71ec98eda131>
 7:45:20 AM: debug Executing 'refresh'
6e3e69f7-27c1-451a-b42a-71ec98eda131
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#6e3e69f7-27c1-451a-b42a-71ec98eda131>
 7:45:20 AM: debug Executing 'poll'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'g'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'i'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'n'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'n'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'o'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected '|'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'C'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected '|'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected ' '
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'G'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'i'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'I'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected '1'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'N'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'N'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'T'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'I'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'O'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'N'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'I'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'O'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'C'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'D'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected '_'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug [[AIR_CONDITIONING|1|Air Conditioning:Air Conditioning]]
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'R'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug getChildDevices(false), children=1
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'I'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Devices Inspected 'A'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Executing parseZoneResponse.successTrue
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Output status: 200
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Executing parseZonesResponse: [[dazzleEnabled:true,
id:1, openWindowDetection:[supported:false], dazzleMode:[supported:false],
deviceTypes:[WR01], name:Air Conditioning, reportAvailable:false,
dateCreated:2017-09-28T06:57:23.111Z,
devices:[[accessPointWiFi:[ssid:tado9712],
currentFwVersion:45.6, serialNo:WR1507FT01002988179713,
connectionState:[timestamp:2017-09-29T05:26:51.171Z, value:true],
shortSerialNo:WR2988179713, deviceType:WR01, characteristics:[capabilities:
[INSIDE_TEMPERATURE_MEASUREMENT]], duties:[ZONE_UI, ZONE_DRIVER,
ZONE_LEADER], commandTableUploadState:FINISHED]], type:AIR_CONDITIONING,
supportsDazzle:false]]
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Executing 'sendCommand'
e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#e8ab2d3f-3b12-4b82-8a19-bac6a5e0528e>
 7:45:16 AM: debug Http Params ([uri:https://my.tado.com,
path:/api/v2/homes/xxx/zones, requestContentType:application/json,
query:[username:xxx@gmail.com, password:xxx]])

Regards,
Roderick Bartolo
M: +356 79251176 <7925%201176>
Skype: rodbartolo
E: rodbartolo@gmail.com

**Comment by fuzzysb** [comment]
Sorry, i have been busy, i have finally looked into this.. i have deleted my install completely and re-installed. I cannot replicate the issue. the devices parse correctly. can you please try and re-add again. maybe a copy/paste issue?

**Comment by fuzzysb** [comment]
Fixed in Latest Commit
