### ISSUE TITLE
Missing Thermostat

### ISSUE THREAD

**Issue by filoor** [fuzzysb/Tado#6]
Hi,

 I have 2 Tado smart radiator buttons in the living room and connected to tado thermostat as a group 
Now i will see the radiator buttons in smartthings but not the Thermostat.

and i want to control the thermostat .

**Comment by fuzzysb** [comment]
If you group the TRV and Thermostat together it will appear as a single device only. this is the way the API works.

what you probably need to do is work it the way i do mine. I have TRV's in a room/zone grouped together under say Living Room, and then i have my Thermostat seperate.

so what happens, is if the TRV temp drops below the threshold for heat it calls heat, and tados platform knows to call heat via the Thermostat connected to the boiler.

likewise if you specify the thermostat heat to be 25 degrees and the TRV's only 20, the TRV's will close to prevent heat being distributed to that zone.

you should not group all together IMHO
